apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nurgiza/node-frontend:latest
          ports:
            - containerPort: 3000  # Changed from 80 (React typically runs on 3000)
          env:
            - name: REACT_APP_API_URL
              value: "http://backend.default.svc.cluster.local:80"  # Full internal DNS
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000  # Must match containerPort
            initialDelaySeconds: 15  # Increased for React startup
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000  # Must match containerPort
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:  # Added for React apps
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # External Port
      targetPort: 3000  # Must match containerPort