apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage-mongo-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # Ensure this matches with PV


