apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==         # mongoadmin
  mongo-root-password: cGFzc3dvcmQxMjM=         # password123
