jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NURI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NURI }}
          region: ${{ secrets.AWS_REGION_NURI }} # Ensure the region is specified here

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION _NURI}} --name proshop-eks

      - name: Get Kubernetes Nodes
        run: |
          kubectl get nodes
